### ISSUE TITLE
To block application window closing until project has been saved

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#18]
As discussed in mail on Nov, 4th:

When the user closes the window, to avoid to close it until the current project is completely saved (show related loading message).

**Comment by andreykruglyak** [comment]
The problem that triggered this discussion was due to an unrelated issue, two users saving the same project to a network disk, which is not supported.

When the user closes the main window, the application does not exit until the project has been saved, it continues work in the background for a couple of seconds with no window shown. This can be changed so that the main window is prevented from closing while saving the current project and a clear "Saving" message is shown to the user. This is already done for SubRel projects, but there the user is asked if he/she would like to save the changes.

**Comment by andreykruglyak** [comment]
Fixed in version 1.1.0.0.
